CREATE TABLE post (
    postid SERIAL PRIMARY KEY,
    "owner" VARCHAR(50),
    message VARCHAR(350),
    class VARCHAR(50),
    created DATETIME DEFAULT CURRENT_TIMESTAMP, 
    FOREIGN KEY ("owner") REFERENCES users(username) ON DELETE CASCADE    
    
);

CREATE TABLE users (
    username VARCHAR(50) PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone_num VARCHAR(20) NOT NULL,
    profile_picture BYTEA
);



class table, 